- name: variables
  hosts: local
  connection: local
  vars_files:
  - vardetails.yaml
  tasks:
  - name: print your details
    vars:
      city: "khammam"
    ansible.builtin.debug:
      msg: "i live in {{state}} : {{city}} : {{country}}"   
