- name: data types
  hosts: local
  connection: local
  vars:
    COUNTRY: "india" # string
    GDP: 4 # int
    IS_TRUE: true # bool
    STATES: #maps/dictionaries {}
      TELANGANA: Hyderabad
      KARNATAKA: Bangalore
      ANDHRA: Vizag
    CITIES: # list []
    - khammam
    - wrngl
  tasks:
  - name: print data types
    ansible.builtin.debug:
      msg: |
        COUNTRY: {{COUNTRY}}
        gdp: {{GDP}}
        istrue: {{IS_TRUE}}
        states: {{STATES}}
        Cities{{CITIES}}
        