- name: loops test
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install servers
    ansible.builtin.package:
      name: "{{item}}"
      status: present
    loop:
    - mysql
    - nginx
