- name: test filters
  hosts: local
  connection: local
  vars: 
    topics: linux, shell, ansible
  tasks:
  - name: print greetings
    ansible.builtin.debug:
      msg: "Hi mam, {{ Greetings | default('good evng') }}" 
  - name: string to lists
    ansible.builtin.debug:
      msg: "{{ topics | split (',') }}"
      
      