- name: error handling
  hosts: local
  connection: local
  tasks:
  - name: check user exists or not
    ansible.builtin.command:
      id roboshop
    register: user_output
    ignore_errors: true
  - name: print user datails
    ansible.builtin.debug:
      msg: "{{ user_output }}"
  